services:
  socials-db:
    image: postgres:15
    container_name: socials-db
    ports:
      - 5432:5432
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: socials-node
